const source = (url, note) => ({
  provider: "参考资料",
  url,
  updatedAt: "2026-10-04",
  note,
});
export const featured = [
  {
    id: "ref-fuji",
    name: "富士山",
    city: "河口湖",
    country: "日本",
    address: "山梨县 · 河口湖地区",
    location: { lng: 138.7274, lat: 35.3606, coordSystem: "WGS84" },
    overview:
      "在河口湖畔远望富士山，沿岸散步，在咖啡馆留一段慢下来的时间。富士山的登山季、登山口及预约要求需要在出发前查阅官方公告。",
    category: "自然风景",
    photo: "/images/fuji.png",
    suggestedMinutes: 120,
    openingHours: null,
    price: null,
    currency: "JPY",
    source: source(
      "https://www.fujisan-climb.jp/",
      "设计参考目的地；当前高德配置仅覆盖国内，海外路线暂不核验。",
    ),
  },
  {
    id: "ref-andes",
    name: "安第斯山脉",
    city: "安第斯地区",
    country: "南美洲",
    address: "南美洲西部",
    location: { lng: -70.1, lat: -32.8, coordSystem: "WGS84" },
    overview:
      "安第斯山脉纵贯南美洲西部，雪山、高原与湖泊构成了多样的自然景观。它是跨越多个国家的山系，制定行程前请先选择具体国家、城市和景点。",
    category: "自然风景",
    photo: "/images/andes.png",
    suggestedMinutes: 180,
    openingHours: null,
    price: null,
    currency: "USD",
    source: source(
      "https://www.britannica.com/place/Andes-Mountains",
      "设计参考目的地；坐标为山系示意位置，不能作为导航终点。",
    ),
  },
];
export const demoPlaces = [
  {
    ...featured[0],
    id: "demo-oishi",
    name: "大石公园",
    address: "河口湖北岸",
    location: { lng: 138.7453, lat: 35.5222, coordSystem: "WGS84" },
    overview:
      "在河口湖北岸远望富士山，沿湖散步。此条目用于展示设计与行程交互，出行前请核对当地官方信息。",
  },
  {
    ...featured[0],
    id: "demo-asakusa",
    name: "浅草寺",
    city: "东京",
    address: "东京 · 浅草",
    location: { lng: 139.7966, lat: 35.7148, coordSystem: "WGS84" },
    photo: "",
    overview: "东京浅草的历史寺院。此条目用于展示设计与行程交互。",
  },
  {
    ...featured[0],
    id: "demo-ueno",
    name: "上野公园",
    city: "东京",
    address: "东京 · 上野",
    location: { lng: 139.7741, lat: 35.7141, coordSystem: "WGS84" },
    photo: "",
    overview:
      "在公园散步，也可按兴趣选择周边博物馆。此条目用于展示设计与行程交互。",
  },
];
export const demoTrip = {
  id: "demo",
  title: "东京 · 富士山",
  city: "东京 · 河口湖",
  summary: "你的 3 日慢游攻略",
  preferences: {
    pace: "relaxed",
    interests: ["自然风景"],
    travelers: 2,
    budget: null,
    transport: "transit",
  },
  createdAt: "2026-10-04T00:00:00Z",
  updatedAt: "2026-10-04T00:00:00Z",
  days: [
    {
      index: 1,
      date: null,
      title: "在东京，慢慢走",
      items: [
        {
          id: "d1-1",
          kind: "place",
          placeId: "demo-asakusa",
          title: "浅草寺",
          arrival: "09:30",
          durationMinutes: 90,
          notes: "逛逛浅草的街巷",
        },
        {
          id: "d1-2",
          kind: "break",
          placeId: null,
          title: "午餐与休息",
          arrival: "12:00",
          durationMinutes: 60,
          notes: "留一段自由安排的时间",
        },
        {
          id: "d1-3",
          kind: "place",
          placeId: "demo-ueno",
          title: "上野公园",
          arrival: "14:00",
          durationMinutes: 120,
          notes: "沿着绿荫散步",
        },
      ],
    },
    {
      index: 2,
      date: null,
      title: "湖畔漫步，看见富士山",
      items: [
        {
          id: "d2-1",
          kind: "place",
          placeId: "demo-oishi",
          title: "大石公园",
          arrival: "09:30",
          durationMinutes: 90,
          notes: "河口湖北岸 · 湖景与富士山",
        },
        {
          id: "d2-2",
          kind: "break",
          placeId: null,
          title: "湖畔午餐与咖啡",
          arrival: "12:00",
          durationMinutes: 60,
          notes: "留一段时间，慢慢看风景",
        },
      ],
    },
    {
      index: 3,
      date: null,
      title: "把最后一天，留给喜欢的地方",
      items: [
        {
          id: "d3-1",
          kind: "place",
          placeId: "demo-ueno",
          title: "上野公园",
          arrival: "10:00",
          durationMinutes: 90,
          notes: "按自己的节奏出发",
        },
        {
          id: "d3-2",
          kind: "break",
          placeId: null,
          title: "返程前的自由时间",
          arrival: "12:00",
          durationMinutes: 120,
          notes: "预留往返机场的时间",
        },
      ],
    },
  ],
};
